[template]
src = "bugzilla-ses-password.tmpl"
dest = "/var/run/bugzilla-ses-password"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0700"

keys = [
    "/config"
]

reload_cmd = "/var/run/bugzilla-ses-password"
