[template]
src = "bugzilla-relayhost.tmpl"
dest = "/var/run/bugzilla-relayhost.pp"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0600"

keys = [
    "/config"
]

reload_cmd = "puppet apply /var/run/bugzilla-relayhost.pp"
