[template]
src = "bugzilla-params.tmpl"
dest = "/var/www/bugzilla-params"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

uid = 0
gid = 48
mode = "0640"

keys = [
    "/config"
]

reload_cmd = "/usr/local/bin/bugzilla-params-update"
